# Generated by Django 5.2.1 on 2026-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='form_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на форму оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Наш ID платежа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID платежа в шлюзе'),
        ),
    ]
