# Generated by Django 5.2.1 on 2026-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_form_url_payment_invoice_id_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Выключите, чтобы временно вернуться к оплате через менеджера.', verbose_name='Принимать онлайн-оплату')),
                ('account', models.CharField(blank=True, help_text='Для теста — с суффиксом «-sandbox».', max_length=100, verbose_name='Account (имя мерчант-аккаунта)')),
                ('merchant_key', models.CharField(blank=True, max_length=200, verbose_name='Merchant Key (логин API)')),
                ('secret', models.CharField(blank=True, help_text='Хранится в базе. Не показывается после сохранения.', max_length=255, verbose_name='Secret (пароль API и ключ подписи)')),
                ('api_base', models.URLField(blank=True, default='https://api-gateway.smartcore.pro', help_text='Меняйте, только если у вашего аккаунта другой домен API.', verbose_name='Адрес API шлюза')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки онлайн-оплаты',
                'verbose_name_plural': 'Настройки онлайн-оплаты',
            },
        ),
    ]
