# Generated by Django 5.2.1 on 2026-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Black Pepper Flower Bar', max_length=150, verbose_name='Название точки')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Точка магазина',
                'verbose_name_plural': 'Точки магазина',
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['radius_from_km', 'order'], 'verbose_name': 'Зона доставки', 'verbose_name_plural': 'Зоны доставки'},
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Время доставки, мин'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='radius_from_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='От, км'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='radius_to_km',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='До, км'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название зоны'),
        ),
    ]
