# Generated by Django 5.2.1 on 2026-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_shoplocation_alter_deliveryzone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='price_on_request',
            field=models.BooleanField(default=False, help_text='Фиксированной цены нет: заказ уходит менеджеру, он согласует стоимость (например, для дальних адресов — за городом).', verbose_name='Доставка по согласованию'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Не заполняется, если доставка по согласованию с менеджером.', max_digits=10, null=True, verbose_name='Цена доставки, ₸'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='radius_from_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='От, км'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='radius_to_km',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7, verbose_name='До, км'),
        ),
    ]
