# Generated by Django 5.2.1 on 2026-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryzone_price_on_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplocation',
            name='name',
            field=models.CharField(default='Blackpepper Flower Bar', max_length=150, verbose_name='Название точки'),
        ),
    ]
