import io
from unittest.mock import patch

from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse
from PIL import Image

from .models import Category, Product
from .utils import shuffle


def _make_test_image():
    buf = io.BytesIO()
    Image.new('RGB', (10, 10), '#BE9554').save(buf, format='JPEG')
    return SimpleUploadedFile('test.jpg', buf.getvalue(), content_type='image/jpeg')


class CategoryModelTests(TestCase):
    def test_slug_autogenerated_from_unicode_name(self):
        category = Category.objects.create(name='Монобукеты')
        self.assertEqual(category.slug, 'монобукеты')


class ProductModelTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Авторские')

    def test_slug_autogenerated_from_unicode_name(self):
        product = Product.objects.create(
            name='Дикий сад', category=self.category, price=21500, in_stock=True,
        )
        self.assertEqual(product.slug, 'дикий-сад')

    def test_in_stock_true_by_default(self):
        product = Product.objects.create(
            name='Белый шёлк', category=self.category, price=16000, in_stock=True,
        )
        self.assertTrue(product.in_stock)

    def test_in_stock_false_when_marked_out(self):
        product = Product.objects.create(
            name='Бархат Бордо', category=self.category, price=24000, in_stock=False,
        )
        self.assertFalse(product.in_stock)


class ProductCompositionTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Авторские')

    def test_empty_composition_is_empty_list(self):
        product = Product.objects.create(name='Букет', category=self.category, price=10000)
        self.assertEqual(product.composition_lines, [])

    def test_comma_separated_single_line(self):
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000,
            composition='Роза 1, Пионы 2, Хризантемы 5',
        )
        self.assertEqual(product.composition_lines, ['Роза 1', 'Пионы 2', 'Хризантемы 5'])

    def test_one_flower_per_line(self):
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000,
            composition='Роза 1\nПионы 2\nХризантемы 5',
        )
        self.assertEqual(product.composition_lines, ['Роза 1', 'Пионы 2', 'Хризантемы 5'])

    def test_multiline_ignores_blank_lines(self):
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000,
            composition='Роза 1\n\n  Пионы 2  \n',
        )
        self.assertEqual(product.composition_lines, ['Роза 1', 'Пионы 2'])


class ProductMultiCategoryTests(TestCase):
    def setUp(self):
        self.primary = Category.objects.create(name='Авторские')
        self.extra = Category.objects.create(name='Монобукеты')
        self.other = Category.objects.create(name='Свадебные')

    def test_all_categories_includes_primary_and_extra(self):
        product = Product.objects.create(name='Букет', category=self.primary, price=10000)
        product.extra_categories.add(self.extra)
        self.assertEqual(product.all_categories, [self.primary, self.extra])

    def test_all_categories_without_extra_is_just_primary(self):
        product = Product.objects.create(name='Букет', category=self.primary, price=10000)
        self.assertEqual(product.all_categories, [self.primary])

    def test_all_categories_deduplicates_primary_added_as_extra_too(self):
        product = Product.objects.create(name='Букет', category=self.primary, price=10000)
        product.extra_categories.add(self.primary, self.extra)
        self.assertEqual(product.all_categories, [self.primary, self.extra])

    def test_category_page_shows_product_via_primary_category(self):
        product = Product.objects.create(
            name='Букет', category=self.primary, price=10000, in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        resp = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.primary.slug])
        )
        self.assertIn(product, resp.context['products'])

    def test_category_page_shows_product_via_extra_category(self):
        product = Product.objects.create(
            name='Букет', category=self.primary, price=10000, in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        product.extra_categories.add(self.extra)
        resp = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.extra.slug])
        )
        self.assertIn(product, resp.context['products'])

    def test_category_page_does_not_show_unrelated_product(self):
        product = Product.objects.create(
            name='Букет', category=self.primary, price=10000, in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        resp = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.other.slug])
        )
        self.assertNotIn(product, resp.context['products'])

    def test_product_in_two_categories_appears_only_once_per_page(self):
        product = Product.objects.create(
            name='Букет', category=self.primary, price=10000, in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        product.extra_categories.add(self.extra)
        resp = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.primary.slug])
        )
        shown = list(resp.context['products'])
        self.assertEqual(shown.count(product), 1)

    def test_product_detail_page_shows_all_category_names(self):
        product = Product.objects.create(
            name='Дикий сад', category=self.primary, price=10000, in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        product.extra_categories.add(self.extra)
        html = self.client.get(reverse('catalog:product_detail', args=[product.slug])).content.decode()
        self.assertIn(self.primary.name, html)
        self.assertIn(self.extra.name, html)


class ProductDiscountTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Авторские')

    def test_no_discount_price_means_not_on_sale(self):
        product = Product.objects.create(name='Букет', category=self.category, price=10000)
        self.assertFalse(product.is_on_sale)
        self.assertEqual(product.effective_price, 10000)
        self.assertEqual(product.discount_percent, 0)

    def test_discount_price_below_price_is_on_sale(self):
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000, discount_price=8000,
        )
        self.assertTrue(product.is_on_sale)
        self.assertEqual(product.effective_price, 8000)
        self.assertEqual(product.discount_percent, 20)

    def test_discount_price_equal_to_price_is_not_on_sale(self):
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000, discount_price=10000,
        )
        self.assertFalse(product.is_on_sale)
        self.assertEqual(product.effective_price, 10000)

    def test_discount_price_above_price_is_not_on_sale(self):
        # Например, цену подняли, а скидочную цену забыли поднять следом.
        product = Product.objects.create(
            name='Букет', category=self.category, price=10000, discount_price=12000,
        )
        self.assertFalse(product.is_on_sale)
        self.assertEqual(product.effective_price, 10000)


class ProductAdminDiscountTests(TestCase):
    def setUp(self):
        from django.contrib.auth.models import User

        self.superuser = User.objects.create_superuser('owner', 'owner@example.com', 'pass12345')
        self.category = Category.objects.create(name='Авторские')
        self.sale_product = Product.objects.create(
            name='Со скидкой', category=self.category, price=10000, discount_price=7500,
            image=_make_test_image(),
        )
        self.regular_product = Product.objects.create(
            name='Без скидки', category=self.category, price=10000,
            image=_make_test_image(),
        )

    def test_on_sale_filter_yes_shows_only_discounted(self):
        self.client.force_login(self.superuser)
        response = self.client.get(reverse('admin:catalog_product_changelist'), {'on_sale': 'yes'})
        shown = {p.pk for p in response.context['cl'].queryset}
        self.assertEqual(shown, {self.sale_product.pk})

    def test_on_sale_filter_no_excludes_discounted(self):
        self.client.force_login(self.superuser)
        response = self.client.get(reverse('admin:catalog_product_changelist'), {'on_sale': 'no'})
        shown = {p.pk for p in response.context['cl'].queryset}
        self.assertEqual(shown, {self.regular_product.pk})

    def test_changelist_shows_discount_badge_only_for_sale_product(self):
        self.client.force_login(self.superuser)
        html = self.client.get(reverse('admin:catalog_product_changelist')).content.decode()
        self.assertIn('-25%', html)


class ShuffleUtilTests(TestCase):
    def test_returns_new_list_without_mutating_source(self):
        source = [1, 2, 3, 4, 5]
        result = shuffle(source)
        self.assertIsInstance(result, list)
        self.assertIsNot(result, source)
        self.assertEqual(source, [1, 2, 3, 4, 5])
        self.assertCountEqual(result, source)

    def test_accepts_any_iterable(self):
        result = shuffle(x for x in range(6))
        self.assertCountEqual(result, list(range(6)))

    def test_eventually_reorders(self):
        source = list(range(30))
        self.assertTrue(any(shuffle(source) != source for _ in range(20)))


class CatalogOrderingTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.authored = Category.objects.create(name='Авторские', slug='avtorskie')
        cls.mono = Category.objects.create(name='Монобукеты', slug='monobukety')
        cls.products = []
        for i in range(8):
            cls.products.append(Product.objects.create(
                name=f'Авторский {i}', slug=f'a-{i}', category=cls.authored,
                price=10000 + i * 1000, in_stock=True, is_active=True,
                is_popular=(i % 2 == 0), image=_make_test_image(),
            ))
        for i in range(6):
            cls.products.append(Product.objects.create(
                name=f'Моно {i}', slug=f'm-{i}', category=cls.mono,
                price=5000 + i * 500, in_stock=True, is_active=True,
                is_popular=(i < 2), image=_make_test_image(),
            ))

    def test_all_section_puts_every_popular_before_every_regular(self):
        resp = self.client.get(reverse('catalog:product_list'))
        shown = list(resp.context['products'])
        flags = [p.is_popular for p in shown]
        # После первого не-популярного не должно встречаться популярных.
        first_regular = flags.index(False)
        self.assertNotIn(True, flags[first_regular:])
        self.assertEqual(sum(flags), Product.objects.filter(is_popular=True).count())
        self.assertEqual(len(shown), Product.objects.count())

    def test_all_section_shuffles_both_groups(self):
        calls = []

        def spy(array):
            items = list(array)
            calls.append(items)
            return items

        with patch('catalog.views.shuffle', side_effect=spy):
            self.client.get(reverse('catalog:product_list'))
        # Один вызов на популярные, один на остальные.
        self.assertEqual(len(calls), 2)
        self.assertTrue(all(p.is_popular for p in calls[0]))
        self.assertTrue(all(not p.is_popular for p in calls[1]))

    def test_category_page_shuffles_and_shows_only_that_category(self):
        with patch('catalog.views.shuffle', side_effect=lambda a: list(a)) as mocked:
            resp = self.client.get(
                reverse('catalog:product_list_by_category', args=['avtorskie'])
            )
        mocked.assert_called_once()
        shown = list(resp.context['products'])
        self.assertEqual(
            {p.pk for p in shown},
            set(Product.objects.filter(category=self.authored).values_list('pk', flat=True)),
        )

    def test_explicit_sort_overrides_random_and_popular_float(self):
        with patch('catalog.views.shuffle') as mocked:
            resp = self.client.get(reverse('catalog:product_list'), {'sort': 'price_asc'})
        mocked.assert_not_called()
        prices = [p.price for p in resp.context['products']]
        self.assertEqual(prices, sorted(prices))

    def test_category_dropdown_lists_all_categories_and_marks_current(self):
        # Компактный выпадающий список (мобилка) — та же информация, что
        # и в ряду чипов (десктоп), просто другая разметка.
        html = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.mono.slug])
        ).content.decode()
        self.assertIn('catalog-category-dropdown', html)
        self.assertIn(self.authored.name, html)
        self.assertIn(self.mono.name, html)
        dropdown_html = html.split('catalog-category-dropdown__list')[1]
        self.assertIn(f'is-active">{self.mono.name}', dropdown_html)


class CatalogSearchTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Авторские')
        self.rose = Product.objects.create(
            name='Розовый рассвет', category=self.category, price=15000,
            composition='Роза 15, Эвкалипт 3', in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        self.tulip = Product.objects.create(
            name='Весенний бриз', category=self.category, price=12000,
            composition='Тюльпан 25', in_stock=True, is_active=True,
            image=_make_test_image(),
        )

    def test_search_matches_by_name(self):
        resp = self.client.get(reverse('catalog:product_list'), {'q': 'рассвет'})
        self.assertEqual(list(resp.context['products']), [self.rose])

    def test_search_matches_by_composition(self):
        resp = self.client.get(reverse('catalog:product_list'), {'q': 'тюльпан'})
        self.assertEqual(list(resp.context['products']), [self.tulip])

    def test_search_is_case_insensitive(self):
        resp = self.client.get(reverse('catalog:product_list'), {'q': 'РОЗА'})
        self.assertEqual(list(resp.context['products']), [self.rose])

    def test_search_with_no_matches_shows_empty_message(self):
        resp = self.client.get(reverse('catalog:product_list'), {'q': 'орхидея'})
        self.assertEqual(list(resp.context['products']), [])
        self.assertContains(resp, 'ничего не найдено')

    def test_search_combines_with_category_filter(self):
        other = Category.objects.create(name='Монобукеты')
        Product.objects.create(
            name='Розовый монобукет', category=other, price=9000,
            composition='Роза 21', in_stock=True, is_active=True,
            image=_make_test_image(),
        )
        resp = self.client.get(
            reverse('catalog:product_list_by_category', args=[self.category.slug]), {'q': 'роза'},
        )
        self.assertEqual(list(resp.context['products']), [self.rose])

    def test_search_box_keeps_the_typed_query(self):
        html = self.client.get(reverse('catalog:product_list'), {'q': 'рассвет'}).content.decode()
        self.assertIn('value="рассвет"', html)
