from django.test import TestCase

from .models import Category, Product


class CategoryModelTests(TestCase):
    def test_slug_autogenerated_from_unicode_name(self):
        category = Category.objects.create(name='Монобукеты')
        self.assertEqual(category.slug, 'монобукеты')


class ProductModelTests(TestCase):
    def setUp(self):
        self.category = Category.objects.create(name='Авторские')

    def test_slug_autogenerated_from_unicode_name(self):
        product = Product.objects.create(
            name='Дикий сад', category=self.category, price=21500, in_stock=True,
        )
        self.assertEqual(product.slug, 'дикий-сад')

    def test_in_stock_true_by_default(self):
        product = Product.objects.create(
            name='Белый шёлк', category=self.category, price=16000, in_stock=True,
        )
        self.assertTrue(product.in_stock)

    def test_in_stock_false_when_marked_out(self):
        product = Product.objects.create(
            name='Бархат Бордо', category=self.category, price=24000, in_stock=False,
        )
        self.assertFalse(product.in_stock)
