# Generated by Django 5.2.1 on 2026-08-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('actor_repr', models.CharField(blank=True, max_length=200, verbose_name='Кто (снимок)')),
                ('actor_role', models.CharField(choices=[('owner', 'Владелец'), ('director', 'Директор'), ('seller', 'Продавец'), ('system', 'Система'), ('anon', 'Не авторизован')], db_index=True, max_length=20, verbose_name='Роль')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('bulk_action', 'Массовое действие'), ('login', 'Вход'), ('logout', 'Выход'), ('login_failed', 'Неудачный вход'), ('password_change', 'Смена пароля'), ('activate', 'Активация аккаунта'), ('deactivate', 'Деактивация аккаунта'), ('export', 'Выгрузка данных'), ('view', 'Просмотр страницы'), ('system', 'Системное событие')], db_index=True, max_length=20, verbose_name='Действие')),
                ('outcome', models.CharField(choices=[('success', 'Успех'), ('denied', 'Отказано'), ('error', 'Ошибка')], default='success', max_length=10, verbose_name='Результат')),
                ('target_object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('target_repr', models.CharField(blank=True, max_length=300, verbose_name='Объект (снимок)')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Контекст')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('request_path', models.CharField(blank=True, max_length=400, verbose_name='Путь')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Метод')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_17d98a_idx'), models.Index(fields=['actor_role', '-timestamp'], name='audit_audit_actor_r_70a62f_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='audit_audit_target__1e9cda_idx')],
            },
        ),
    ]
