# Generated by Django 5.2.1 on 2026-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True, verbose_name='Слаг (для URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=210, unique=True, verbose_name='Слаг (для URL)'),
        ),
    ]
