# Generated by Django 5.2.1 on 2026-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
    ]
