# Generated by Django 5.2.1 on 2026-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее букет в карусели на главной. При одинаковых числах сначала идут более новые.', verbose_name='Порядок в «Популярных сборках»'),
        ),
    ]
