# Generated by Django 5.2.1 on 2026-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Короткая строка под названием на карточке категории (напр. «Букеты для особенных моментов»).', max_length=200, verbose_name='Подпись под названием'),
        ),
    ]
