# Generated by Django 5.2.1 on 2026-09-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заполните, чтобы включить скидку — товар начнёт показываться по этой цене везде (каталог, карточка, корзина, заказ) с зачёркнутой обычной ценой рядом. Оставьте пустым или больше/равно обычной цене — скидка не действует.', max_digits=10, null=True, verbose_name='Цена со скидкой, ₸'),
        ),
    ]
