# Generated by Django 5.2.1 on 2026-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, help_text='Товар дополнительно покажется и в этих категориях — основная категория (поле выше) не дублируется, указывать её здесь не нужно.', related_name='extra_products', to='catalog.category', verbose_name='Дополнительные категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, help_text='Через запятую в одну строку («Роза 1, Пионы 2, Хризантемы 5») или по одному цветку на строке — оба формата работают одинаково.', verbose_name='Состав'),
        ),
    ]
