# Generated by Django 5.2.1 on 2026-10-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_extra_categories_alter_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядок в карусели на главной: 1 — первым, 2 — вторым и т.д. Товары без номера идут после пронумерованных (сначала новые).', null=True, verbose_name='Позиция в «Популярных сборках»'),
        ),
    ]
