# Generated by Django 5.2.1 on 2026-10-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_popular_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Необязательно. Если пусто — собирается автоматически.', max_length=170, verbose_name='SEO-описание (для сниппета в поиске)'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text',
            field=models.TextField(blank=True, help_text='Текст на 1000–2000 знаков внизу страницы категории: о чём эти букеты, для кого и для какого повода. Абзацы — через пустую строку.', verbose_name='SEO-текст под товарами'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Необязательно. Если пусто — собирается автоматически из названия.', max_length=70, verbose_name='SEO-заголовок (title)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Необязательно. Если пусто — собирается автоматически из состава и цены.', max_length=170, verbose_name='SEO-описание (для сниппета в поиске)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Необязательно. Если пусто — собирается автоматически.', max_length=70, verbose_name='SEO-заголовок (title)'),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Что это за букет простыми словами — например «Букет с кустовыми розами, маттиолой и эрингиумом». Выводится под названием и попадает в заголовок страницы: по английскому названию букеты не ищут.', max_length=160, verbose_name='Подзаголовок (по-русски)'),
        ),
    ]
