# Generated by Django 5.2.1 on 2026-10-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_seo_description_category_seo_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(db_index=True, max_length=210, verbose_name='Прежний slug')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='catalog.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Редирект со старого адреса',
                'verbose_name_plural': 'Редиректы со старых адресов',
            },
        ),
    ]
