# Generated by Django 5.2.1 on 2026-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписался')),
            ],
            options={
                'verbose_name': 'Подписчик рассылки',
                'verbose_name_plural': 'Подписчики рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
