# Generated by Django 5.2.1 on 2026-08-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
