# Generated by Django 5.2.1 on 2026-08-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('processing', 'Собирается'), ('delivered', 'Доставлен'), ('payment_failed', 'Ошибка оплаты')], default='new', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(blank=True, help_text='Например: «14:00–16:00»', max_length=50, verbose_name='Время доставки')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки, ₸')),
                ('card_text', models.TextField(blank=True, verbose_name='Текст открытки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма, ₸')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.deliveryzone', verbose_name='Зона доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент заказа, ₸')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
