# Generated by Django 5.2.1 on 2026-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'Собирается'), ('delivered', 'Доставлен'), ('payment_failed', 'Ошибка оплаты')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
