# Generated by Django 5.2.1 on 2026-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Выключите, чтобы временно остановить уведомления, не стирая токен.', verbose_name='Отправлять уведомления')),
                ('bot_token', models.CharField(blank=True, help_text='Выдаёт @BotFather в Telegram после команды /newbot.', max_length=100, verbose_name='Токен бота')),
                ('chat_id', models.CharField(blank=True, help_text='Куда слать уведомления — чат с ботом или группа. Можно найти кнопкой ниже.', max_length=64, verbose_name='Chat ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Telegram-уведомлений',
                'verbose_name_plural': 'Настройки Telegram-уведомлений',
            },
        ),
    ]
