# Generated by Django 5.2.1 on 2026-09-22 08:42, переупорядочено вручную —
# сначала создаём TelegramRecipient и переносим туда старый chat_id (если он
# был заполнен), и только потом удаляем поле из TelegramSettings.

import django.db.models.deletion
from django.db import migrations, models


def _copy_chat_id_to_recipient(apps, schema_editor):
    TelegramSettings = apps.get_model('notify', 'TelegramSettings')
    TelegramRecipient = apps.get_model('notify', 'TelegramRecipient')
    row = TelegramSettings.objects.filter(pk=1).first()
    if row is not None and row.chat_id:
        TelegramRecipient.objects.get_or_create(
            chat_id=row.chat_id, defaults={'settings_id': 1},
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='Можно найти автоматически кнопкой на странице настроек.', max_length=64, unique=True, verbose_name='Chat ID')),
                ('label', models.CharField(blank=True, help_text='Например «Директор» или «Чат продавцов» — чтобы не путать получателей.', max_length=100, verbose_name='Название (для себя)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('settings', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notify.telegramsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
                'ordering': ['label', 'chat_id'],
            },
        ),
        migrations.RunPython(_copy_chat_id_to_recipient, _noop),
        migrations.RemoveField(
            model_name='telegramsettings',
            name='chat_id',
        ),
    ]
